<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Salary Process</name>
   <tag></tag>
   <elementGuidId>2458eb38-301f-4c03-b6d2-f35aab18f4e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='HRPortal_TH_wt231_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt102_block_RichWidgets_wtSalaryProcess_block_wtDropDownButtonElement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HRPortal_TH_wt231_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt102_block_RichWidgets_wtSalaryProcess_block_wtDropDownButtonElement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>HRPortal_TH_wt231_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt102_block_RichWidgets_wtSalaryProcess_block_wtDropDownButtonElement</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Menu_TopMenu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>HRPortal_TH_wt231_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt102_block_RichWidgets_wtSalaryProcess_block_wtDropDownPanel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salary Process </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HRPortal_TH_wt231_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt102_block_RichWidgets_wtSalaryProcess_block_wtDropDownButtonElement&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='HRPortal_TH_wt231_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt102_block_RichWidgets_wtSalaryProcess_block_wtDropDownButtonElement']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HRPortal_TH_wt231_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt102_block_RichWidgets_wtSalaryProcess_block_wtDropDownButtonRoot']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Payment Slips'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employees Reports'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[2]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[3]/div</value>
   </webElementXpaths>
</WebElementEntity>
