<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Approve Timesheets</name>
   <tag></tag>
   <elementGuidId>abc90ac2-014d-474c-843d-2fc87904bf3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='HRPortal_TH_wt24_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt68_block_RichWidgets_wtApproveTimeSheet_block_wtMenuItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HRPortal_TH_wt24_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt68_block_RichWidgets_wtApproveTimeSheet_block_wtMenuItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>HRPortal_TH_wt24_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt68_block_RichWidgets_wtApproveTimeSheet_block_wtMenuItem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve Timesheets</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HRPortal_TH_wt24_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt68_block_RichWidgets_wtApproveTimeSheet_block_wtMenuItem&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='HRPortal_TH_wt24_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt68_block_RichWidgets_wtApproveTimeSheet_block_wtMenuItem']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HRPortal_TH_wt24_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt68_block_RichWidgets_wtApproveTimeSheet_block_wtDropDownButtonElement']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheets'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TimeSheets'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management'])[1]/preceding::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
