<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dashboard_Template_IOHub_wt117blockOu_f3a936</name>
   <tag></tag>
   <elementGuidId>d8754d65-eb7b-4eb4-b921-ca57e7e5b313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn1_wtYearFilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn1_wtYearFilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Template_IOHub_wt117$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$OutSystemsUIWeb_wt19$block$wtColumn1$wtYearFilter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2021</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn1_wtYearFilter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn1_wtYearFilter','Template_IOHub_wt117$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$OutSystemsUIWeb_wt19$block$wtColumn1$wtYearFilter','Change','__OSVSTATE,',0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>OsLimitInput(this,event,50);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by year</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt80_block_wtColumn3_wt58', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onoschange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn1_wtYearFilter','Template_IOHub_wt117$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$OutSystemsUIWeb_wt19$block$wtColumn1$wtYearFilter','Change','__OSVSTATE,',osOnChangeTimerDelay);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn1_wtYearFilter&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn1_wtYearFilter']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn1_wtYearFilterAjaxRfrsh']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/input</value>
   </webElementXpaths>
</WebElementEntity>
