<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FirstSecondThirdFourth</name>
   <tag></tag>
   <elementGuidId>90d4a6f8-821f-42f4-aced-e62f96c002a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn2_wtCBQuarter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn2_wtCBQuarter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Template_IOHub_wt117$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$OutSystemsUIWeb_wt19$block$wtColumn2$wtCBQuarter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn2_wtCBQuarter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>34</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select OSFillParent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt80_block_wtColumn3_wt58', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn2_wtCBQuarter','Template_IOHub_wt117$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$OutSystemsUIWeb_wt19$block$wtColumn2$wtCBQuarter','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.onchange();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	First
	Second
	Third
	Fourth

</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn2_wtCBQuarter&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn2_wtCBQuarter']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Template_IOHub_wt117_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wt19_block_wtColumn2']/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEV'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Quarter Status'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
