<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Configurations_Menu_DropDownArrow</name>
   <tag></tag>
   <elementGuidId>dd17ddf0-011a-4bf8-9cda-479e3a2a52e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='HRPortal_TH_wt22_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt48_block_RichWidgets_wt15_block_wtMenuItem']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HRPortal_TH_wt22_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt48_block_RichWidgets_wt15_block_wtMenuItem > span.Menu_DropDownArrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Menu_DropDownArrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HRPortal_TH_wt22_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt48_block_RichWidgets_wt15_block_wtMenuItem&quot;)/span[@class=&quot;Menu_DropDownArrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HRPortal_TH_wt22_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt48_block_RichWidgets_wt15_block_wtMenuItem']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
