<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Salary Process_Menu_DropDownArrow</name>
   <tag></tag>
   <elementGuidId>f3625c09-3441-4a6e-bedd-22aa3ed44eaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='HRPortal_TH_wt52_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt295_block_RichWidgets_wtSalaryProcess_block_wtMenuItem']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HRPortal_TH_wt52_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt295_block_RichWidgets_wtSalaryProcess_block_wtMenuItem > span.Menu_DropDownArrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Menu_DropDownArrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HRPortal_TH_wt52_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt295_block_RichWidgets_wtSalaryProcess_block_wtMenuItem&quot;)/span[@class=&quot;Menu_DropDownArrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HRPortal_TH_wt52_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt295_block_RichWidgets_wtSalaryProcess_block_wtMenuItem']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
