<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Requests_Menu_DropDownArrow</name>
   <tag></tag>
   <elementGuidId>becda8b0-3136-43dd-b0f2-d015ca0443f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='HRPortal_TH_wt46_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt93_block_RichWidgets_wtAllRequests_block_wtMenuItem']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.Menu_DropDownArrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Menu_DropDownArrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HRPortal_TH_wt46_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt93_block_RichWidgets_wtAllRequests_block_wtMenuItem&quot;)/span[@class=&quot;Menu_DropDownArrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HRPortal_TH_wt46_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_HRPortal_TH_wt93_block_RichWidgets_wtAllRequests_block_wtMenuItem']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
