<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout</name>
   <tag></tag>
   <elementGuidId>33e0d71b-31cf-418f-875c-c367f3450a6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtHeader_wtRight_wtRight_Template_IOHub_wt3_block_OutSystemsUIWeb_wt22_block_wtFooter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtHeader_wtRight_wtRight_Template_IOHub_wt3_block_OutSystemsUIWeb_wt22_block_wtFooter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtHeader_wtRight_wtRight_Template_IOHub_wt3_block_OutSystemsUIWeb_wt22_block_wtFooter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>balloon-footer ph</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtHeader_wtRight_wtRight_Template_IOHub_wt3_block_OutSystemsUIWeb_wt22_block_wtFooter&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtHeader_wtRight_wtRight_Template_IOHub_wt3_block_OutSystemsUIWeb_wt22_block_wtFooter']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtHeader_wtRight_wtRight_Template_IOHub_wt3_block_OutSystemsUIWeb_wt22_block_wtBalloonWrapper']/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Célia Roma'])[1]/following::div[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEV'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
