<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Review_TrackHub_Theme_wt191blockTempl_2c1d74</name>
   <tag></tag>
   <elementGuidId>93029a00-8dc3-4620-af7f-e47c5957e88e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt251']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt251</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt251','TrackHub_Theme_wt191$block$Template_IOHub_wt1$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$wtMainContent$wt251','','__OSVSTATE,',''); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TrackHub_Theme_wt191$block$Template_IOHub_wt1$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$wtMainContent$wt251</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reset</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt251</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>89</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button ThemeGrid_Width4 ThemeGrid_MarginGutter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt251&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt251']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TrackHub_Theme_wt191_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wtFilters']/div[4]/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]/div/div[4]/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
