<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This is a Client feedback_HRPortal_TH_3db7ab</name>
   <tag></tag>
   <elementGuidId>d4c19519-0185-4ab5-af7f-347ab5d258f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='HRPortal_TH_wt50_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModal_360Evaluation_block_wtContent_wtEvaluation360_EvaluateOthers_WB_wt8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HRPortal_TH_wt50_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModal_360Evaluation_block_wtContent_wtEvaluation360_EvaluateOthers_WB_wt8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HRPortal_TH_wt50$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$OutSystemsUIWeb_wtModal_360Evaluation$block$wtContent$wtEvaluation360_EvaluateOthers_WB$wt8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>HRPortal_TH_wt50_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModal_360Evaluation_block_wtContent_wtEvaluation360_EvaluateOthers_WB_wt8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button ThemeGrid_Width3 ThemeGrid_MarginGutter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HRPortal_TH_wt50_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModal_360Evaluation_block_wtContent_wtEvaluation360_EvaluateOthers_WB_wt8&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='HRPortal_TH_wt50_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModal_360Evaluation_block_wtContent_wtEvaluation360_EvaluateOthers_WB_wt8']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='HRPortal_TH_wt50_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModal_360Evaluation_block_wtContent_wtEvaluation360_EvaluateOthers_WB']/div[4]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
   </webElementXpaths>
</WebElementEntity>
