<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show Only Open Projects_TrackHub_Them_1c1e11</name>
   <tag></tag>
   <elementGuidId>3ad1a059-7a78-4465-aa38-d4908592f576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_OutSystemsUIWeb_wt15_block_wtContent_OutSystemsUIWeb_wt21_block_wtContent_wt53']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_OutSystemsUIWeb_wt15_block_wtContent_OutSystemsUIWeb_wt21_block_wtContent_wt53</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TrackHub_Theme_wt30$block$Template_IOHub_wt1$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$wtMainContent$OutSystemsUIWeb_wt15$block$wtContent$OutSystemsUIWeb_wt21$block$wtContent$wt53</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_OutSystemsUIWeb_wt15_block_wtContent_OutSystemsUIWeb_wt21_block_wtContent_wt53</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>38</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt79', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_OutSystemsUIWeb_wt15_block_wtContent_OutSystemsUIWeb_wt21_block_wtContent_wt53&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_OutSystemsUIWeb_wt15_block_wtContent_OutSystemsUIWeb_wt21_block_wtContent_wt53']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_OutSystemsUIWeb_wt15_block_wtContent_OutSystemsUIWeb_wt21_block_wtContent']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
