<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show Only Templates Projects_TrackHub_7cd0c5</name>
   <tag></tag>
   <elementGuidId>d7f47059-2892-45f2-81a6-845107677ed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt79']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt79</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt79','TrackHub_Theme_wt30$block$Template_IOHub_wt1$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$wtMainContent$wt79','','__OSVSTATE,',''); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TrackHub_Theme_wt30$block$Template_IOHub_wt1$block$OutSystemsUIWeb_wt16$block$wtContent$wtMainContent$wtMainContent$wt79</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt79</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>40</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Is_Default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt79&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wt79']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wtFilters_Wrapper']/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
