<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_IATDEV</name>
   <tag></tag>
   <elementGuidId>e30110e6-b20d-49b3-bbe3-9654b7bb9e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wtProjectList_ctl18_wt92_OutSystemsUIWeb_wt13_block_wtTitle_wt9']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wtProjectList_ctl18_wt92_OutSystemsUIWeb_wt13_block_wtTitle_wt9 > span.ProjectName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProjectName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IATDEV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wtProjectList_ctl18_wt92_OutSystemsUIWeb_wt13_block_wtTitle_wt9&quot;)/span[@class=&quot;ProjectName&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='TrackHub_Theme_wt30_block_Template_IOHub_wt1_block_OutSystemsUIWeb_wt16_block_wtContent_wtMainContent_wtMainContent_wtProjectList_ctl18_wt92_OutSystemsUIWeb_wt13_block_wtTitle_wt9']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teste Theme Clone 2'])[1]/following::span[21]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teste Theme Clone 1'])[1]/following::span[42]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IATDEV 2'])[1]/preceding::span[21]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clone Projects'])[1]/preceding::span[42]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IATDEV']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
