<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Backoffice_Menu_DropDownArrow</name>
   <tag></tag>
   <elementGuidId>cb8fd9aa-e466-4828-bff3-44bd60f74703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='HRPortal_TH_wt39_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_wt24_RichWidgets_wt29_block_wtMenuItem']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.Menu_DropDownArrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Menu_DropDownArrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HRPortal_TH_wt39_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_wt24_RichWidgets_wt29_block_wtMenuItem&quot;)/span[@class=&quot;Menu_DropDownArrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HRPortal_TH_wt39_block_OutSystemsUIWeb_wt16_block_wtHeader_wtMenu_wt24_RichWidgets_wt29_block_wtMenuItem']/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
   </webElementXpaths>
</WebElementEntity>
